services:
  - type: web
    name: my-portfolio
    env: node
    buildCommand: "npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
